version: '3'

services:

  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  redis:
    image: "redis:alpine"
