version: '2.1'

services:

  web:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    restart: always
    expose:
      - "5000"
    networks:
      - pfl

  postgres:
    image: postgres:10.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: politagsadmin
      POSTGRES_DB: politags
    restart: always
    networks:
      - pfl

  adminer:
    image: adminer:4.3.1-standalone
    restart: always
    networks:
      - pfl
      - nginx-load-balancer

networks:
  pfl:
    external: 
      name: pfl_pfl
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
  
volumes:
  pgdata: