version: '3'

services:

  web:
    build: .
    ports:
      - "5555:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:10.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: politagsadmin
      POSTGRES_DB: politags
    restart: always

  adminer:
    image: adminer:4.3.1-standalone
    restart: always
    ports:
      - 9999:8080
