version: '3'

services:

  web:
    build: .
    ports:
      - "5555:5000"
    volumes:
      - .:/usr/src/app

  db:
    image: mysql:8.0.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: politags

  adminer:
    image: adminer:4.3.1-standalone
    restart: always
    ports:
      - 9999:8080
