"""drop_topic_columns

Revision ID: 0771140bc85f
Revises: 517f796096a3
Create Date: 2018-02-27 11:09:13.461829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0771140bc85f'
down_revision = '517f796096a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topics_parent_id_fkey', 'topics', type_='foreignkey')
    op.drop_column('topics', 'slug')
    op.drop_column('topics', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('topics_parent_id_fkey', 'topics', 'topics', ['parent_id'], ['id'])
    # ### end Alembic commands ###
