"""empty message

Revision ID: 0d9b8c6d0654
Revises: 2dd000bf6d3c
Create Date: 2018-02-01 12:30:14.257623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9b8c6d0654'
down_revision = '2dd000bf6d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(200), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles_topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
