"""empty message

Revision ID: 2dd000bf6d3c
Revises: 6f6365119d2d
Create Date: 2018-02-01 10:27:34.189256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd000bf6d3c'
down_revision = '6f6365119d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_string', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
