"""empty message

Revision ID: 4358c46d8072
Revises: 0d9b8c6d0654
Create Date: 2018-02-01 12:46:51.406580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4358c46d8072'
down_revision = '0d9b8c6d0654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_topics', sa.Column('initial_certainty', sa.Float(), nullable=True))
    op.add_column('articles_topics', sa.Column('updated_certainty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles_topics', 'updated_certainty')
    op.drop_column('articles_topics', 'initial_certainty')
    # ### end Alembic commands ###
