"""empty message

Revision ID: 517f796096a3
Revises: e0d73ecf862d
Create Date: 2018-02-19 11:52:08.489763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517f796096a3'
down_revision = 'e0d73ecf862d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'topics', 'topics', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'slug')
    # ### end Alembic commands ###
