"""Add created_at to articles table

Revision ID: 6533819d93e2
Revises: 706b54feba92
Create Date: 2017-12-05 11:25:20.693608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6533819d93e2'
down_revision = '706b54feba92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
