"""add sentiment to articles table

Revision ID: 8cfc1b5593fb
Revises: 0771140bc85f
Create Date: 2018-03-08 09:53:41.820449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfc1b5593fb'
down_revision = '0771140bc85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('sentiment_polarity', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('sentiment_subjectivity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'sentiment_subjectivity')
    op.drop_column('articles', 'sentiment_polarity')
    # ### end Alembic commands ###
