"""add column updated_at to verifications

Revision ID: a74150a3dc76
Revises: 517f796096a3
Create Date: 2018-02-26 12:03:08.569015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74150a3dc76'
down_revision = '517f796096a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'updated_at')
    # ### end Alembic commands ###
