"""update politicians model

Revision ID: b2da573fada8
Revises: 8cfc1b5593fb
Create Date: 2018-03-13 10:40:55.073797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2da573fada8'
down_revision = '8cfc1b5593fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicians', sa.Column('gender', sa.String(length=20), server_default='unknown', nullable=False))
    op.drop_column('politicians', 'suffix')
    op.drop_column('politicians', 'department')
    op.drop_column('politicians', 'given_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicians', sa.Column('given_name', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('politicians', sa.Column('department', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('politicians', sa.Column('suffix', sa.VARCHAR(length=20), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('politicians', 'gender')
    # ### end Alembic commands ###