"""empty message

Revision ID: bb0bc279bf4c
Revises: 4358c46d8072
Create Date: 2018-02-07 12:57:19.436909

"""
from alembic import op
import sqlalchemy as sa
from app import db
from sqlalchemy_utils import generic_relationship
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb0bc279bf4c'
down_revision = '4358c46d8072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('responses', 'verifications')

    op.add_column('articles_topics', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('entity_linkings', sa.Column('created_at', sa.DateTime(), nullable=True))

    op.add_column('verifications', sa.Column('verifiable_type', sa.String(50), nullable=True))
    op.add_column('verifications', sa.Column('verifiable_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_linkings', 'created_at')
    op.drop_column('articles_topics', 'created_at')

    op.rename_table('verifications', 'responses')
    op.drop_column('responses', 'verifiable_id')
    op.drop_column('responses', 'verifiable_type')
    # ### end Alembic commands ###
