"""empty message

Revision ID: bb0bc279bf4c
Revises: 4358c46d8072
Create Date: 2018-02-07 12:57:19.436909

"""
from alembic import op
import sqlalchemy as sa
from app.models.models import Verification
from app import db
from sqlalchemy_utils import generic_relationship
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb0bc279bf4c'
down_revision = '4358c46d8072'
branch_labels = None
depends_on = None

class Question(db.Model):
    _tablename_ = 'questions'
    id = db.Column(db.Integer(), primary_key=True)
    article_id = db.Column(db.String(200), db.ForeignKey('articles.id'))
    questionable_type = db.Column(db.String(50))
    questionable_id = db.Column(db.Integer(), nullable=False)
    # Relationships
    questionable_object = generic_relationship(questionable_type, questionable_id)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('responses', 'verifications')

    op.add_column('articles_topics', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('entity_linkings', sa.Column('created_at', sa.DateTime(), nullable=True))

    op.add_column('verifications', sa.Column('verifiable_type', sa.String(50), nullable=True))
    op.add_column('verifications', sa.Column('verifiable_id', sa.Integer(), nullable=True))

    #fill verifiable type and id with the right values.
    verifications = Verification.query.all()

    for verification in verifications:
        question = Question.query.filter(Question.id == verification.question_id)
        verification.questionable_object = question.questionable_object

    op.drop_column('verifications', 'question_id')

    op.drop_table('questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('questionable_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('questionable_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='questions_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='questions_pkey')
    )

    op.drop_column('entity_linkings', 'created_at')
    op.drop_column('articles_topics', 'created_at')

    op.rename_table('verifications', 'responses')
    op.add_column('responses', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('responses', 'verifiable_id')
    op.drop_column('responses', 'verifiable_type')
    # ### end Alembic commands ###
