"""empty message

Revision ID: d67521cba296
Revises: 4df404f78b9f
Create Date: 2018-01-30 14:07:57.816806

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd67521cba296'
down_revision = '4df404f78b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'created_at')
    # ### end Alembic commands ###
